### ISSUE TITLE
Capture Successfully Flashes

### ISSUE THREAD

**Issue by drushbrook** [kueblc/mocktuyacloud#3]
Please open a wiki page to capture device failures, bricks and successes using mocktuyacloud.

I have had success with 3 x Medion Life+ Smart Plug S85225 (**deviceid: 77180230[mac]**)
I have have failed with 2 x Mirabella Genio Wi-Fi Dim Bulb (**deviceid: 14682127[mac]**) - looks like I need to trigger the update with the keys

I have one bricked device 1 x Medion Life+ Smart Plug S85225 (**deviceid: 77180230[mac]**) with firmware 1.1.0 - this was the device I originally captured the firmware update with.

**Comment by kueblc** [comment]
Will do, thanks for reporting! Sorry to hear about the failures, if you have any details on them, logs, etc, please feel free to share.

**Comment by kueblc** [comment]
Take a look at what I've added and feel free to make any corrections or additions

**Comment by drushbrook** [comment]
Fantastic.

**Comment by kueblc** [comment]
Was the only difference in the bricked device the firmware? Do you know what firmware the successfully flashed devices were?

**Comment by drushbrook** [comment]
Yes the firmware was the difference.

**Comment by drushbrook** [comment]
The flash appeared to work however the Final stage said never came up. The
device's led no longer displays, the button no longer works and power is no
longer relayed to the power socket
