### ISSUE TITLE
Mirabella Genio Bulb Failure - Logs and Captures

### ISSUE THREAD

**Issue by drushbrook** [kueblc/mocktuyacloud#4]
Here is the log and captures as per failures mentioned in #3

the tcpdumps are gzipped to allow attachment to the issue.

I provisioned the device and captured both the mobile app traffic and the bulb traffic.
[provision.pcap.gz](https://github.com/kueblc/mocktuyacloud/files/2787455/provision.pcap.gz)

I then rebooted the device and captured the bulb traffic.

[reboot.pcap.gz](https://github.com/kueblc/mocktuyacloud/files/2787457/reboot.pcap.gz)

I have put in both the secKey and the localKey for the bulb in config.js - it redirected but no upgrade request was made - unfortunately I didn't do a network capture of the redirect process.

[bulb.redirect.log](https://github.com/kueblc/mocktuyacloud/files/2787430/bulb.redirect.log)

I then restarted both mocktuyacloud and the device and captured the network.
[log after restart of both mocktuya and bulb.log](https://github.com/kueblc/mocktuyacloud/files/2787450/log.after.restart.of.both.mocktuya.and.bulb.log)

[capture after restart of both mocktuyacloud and reboot of device.pcap.gz](https://github.com/kueblc/mocktuyacloud/files/2787421/capture.after.restart.of.both.mocktuyacloud.and.reboot.of.device.pcap.gz)

**Comment by kueblc** [comment]
Thanks for the report and detailed logs! I'll look into it this afternoon.

**Comment by GeorgeIoak** [comment]
@drushbrook How did you setup your capturing? For me my PC has built-in WiFi and Ethernet so I created a HotSpot on my PC and then had my phone connect to that HotSpot. I then used WireShark to monitor the traffic on the HotSpot interface.

**Comment by drushbrook** [comment]
tcpdump on my router - it runs Tomato by Shibby
