### ISSUE TITLE
New SSID 

### ISSUE THREAD

**Issue by alfem** [kueblc/mocktuyacloud#7]
Hi! 

I wast testing an brand new Digoo NX-SP202 dual socket but it did not connect to fake AP.

After some sniffing, I found out my socket is trying to connect to "tuya_mdev_test2". 

Then I changed the configuration in hostapd to use this new SSID, but wifi key must have been changed as well because the socket does not connect.

**Comment by kueblc** [comment]
Hi @alfem,

Thanks for your report. MockTuyaCloud is mainly of interest for developers and reverse engineers. At this point `tuya-convert` is our maintained solution for firmware flashing, which it looks like you've already found. I'll follow up with you there.

**Comment by alfem** [comment]
Ok, let's jump to tuya-convert repo.
